### ISSUE TITLE
Tried your workaround, this is what I'm getting

### ISSUE THREAD

**Issue by MrDarkness117** [victorkipruto/desktop-automation#1]
```
selenium.common.exceptions.SessionNotCreatedException: Message: A new session could not be created. Details: Session capabilities format must comply to the W3C standard. Make sure your client is up to date. See https://www.w3.org/TR/webdriver/#new-session for more details.
Stacktrace:
SessionNotCreatedError: A new session could not be created. Details: Session capabilities format must comply to the W3C standard. Make sure your client is up to date. See https://www.w3.org/TR/webdriver/#new-session for more details.
    at makeNonW3cCapsError (C:\Users\User\AppData\Roaming\fnm\node-versions\v20.16.0\installation\node_modules\appium\lib\utils.js:32:10)
    at AppiumDriver.createSession (C:\Users\User\AppData\Roaming\fnm\node-versions\v20.16.0\installation\node_modules\appium\lib\appium.js:617:32)
    at runCommandPromise (C:\Users\User\AppData\Roaming\fnm\node-versions\v20.16.0\installation\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:115:20)
    at AppiumDriver.executeCommand (C:\Users\User\AppData\Roaming\fnm\node-versions\v20.16.0\installation\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:149:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at defaultBehavior (C:\Users\User\AppData\Roaming\fnm\node-versions\v20.16.0\installation\node_modules\appium\lib\appium.js:1119:16)
    at AppiumDriver.executeWrappedCommand (C:\Users\User\AppData\Roaming\fnm\node-versions\v20.16.0\installation\node_modules\appium\lib\appium.js:1229:16)
    at AppiumDriver.executeCommand (C:\Users\User\AppData\Roaming\fnm\node-versions\v20.16.0\installation\node_modules\appium\lib\appium.js:1135:17)
    at asyncHandler (C:\Users\User\AppData\Roaming\fnm\node-versions\v20.16.0\installation\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:387:19)
```

All I really did was separately install appium that I apparently didn't have before. Maybe there's something else I forgot to do?

**Comment by MrDarkness117** [comment]
UPD: had Appium running instead of WinAppDriver.

Run WinAppDriver, _not_ appium.
